// Instruments suggested when a group has not listed its own yet, by family: voice, percussion,
// wind and strings. Anything else can be typed as it is called locally.
export const STARTER_INSTRUMENTS = [
  'Canto',
  'Coro',
  'Bombo',
  'Caja',
  'Redoblante',
  'Tamboril',
  'Pandereta',
  'Pandero',
  'Castañuelas',
  'Almirez',
  'Botella de anís',
  'Dulzaina',
  'Gaita',
  'Gaita de fuelle',
  'Flauta',
  'Flauta y tamboril',
  'Acordeón',
  'Guitarra',
  'Laúd',
  'Bandurria',
  'Violín',
  'Rabel',
];
